[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "amentum-librti-workshop"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "streamlit>=1.36",
  "pandas>=2.2",
  "numpy>=1.26",
  "pyyaml>=6.0",
]
